baseurl      = "https://pabu-dev-blog.netlify.app/"
title        = "Pablo Dev"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = """
  Hi, I'm Pablo de Andrade - Software and Web Developer - and this is my blog
  """

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "Pabu-Dev Blog"
  keywords = "homepage, blog"
  images = [""]

    [params.author]
    name = "Pablo Andrade"

    [params.footer]
        trademark = 2024
        rss = false
        copyright = false
        author = false

        topText = []
        bottomText = [
            "Powered by <a href=\"https://www.linkedin.com/in/pablodeas/\">Pablo A.</a>"
        ]

    [params.portrait]
        path = "/images/profile.jpeg"
        alt = "Portrait"
        maxWidth = "200px"
    
    


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.en.params]
    # Subtitle for the Tag of the site
    subtitle  = ""
    readOtherPosts = "Read other posts"
    keywords = ""

    [languages.en.params.logo]
      logoText = "Pablo Dev's Blog"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"